-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.team
(
    team_id integer NOT NULL,
    team_name character varying(80) NOT NULL,
    city character varying(80) NOT NULL,
    CONSTRAINT teamid_pkey PRIMARY KEY (team_id)
);

CREATE TABLE IF NOT EXISTS public.player
(
    player_id integer NOT NULL,
    player_name character varying(100) NOT NULL,
    "position" character varying(50) NOT NULL,
    team_id integer NOT NULL,
    CONSTRAINT playerid_pkey PRIMARY KEY (player_id)
);

CREATE TABLE IF NOT EXISTS public.type
(
    type_id integer NOT NULL,
    type_name character varying(100) NOT NULL,
    CONSTRAINT typeid_pkey PRIMARY KEY (type_id)
);

CREATE TABLE IF NOT EXISTS public.match
(
    match_id integer NOT NULL,
    type_id integer NOT NULL,
    date date NOT NULL,
    "time" time(4) without time zone NOT NULL,
    home_team_id integer NOT NULL,
    away_team_id integer NOT NULL,
    CONSTRAINT matchid_pkey PRIMARY KEY (match_id)
);

CREATE TABLE IF NOT EXISTS public.result
(
    result_id integer NOT NULL,
    match_id integer NOT NULL,
    home_team_goals integer NOT NULL,
    away_team_goals integer NOT NULL,
    CONSTRAINT resultid_pkey PRIMARY KEY (result_id),
    UNIQUE (match_id)
);

ALTER TABLE IF EXISTS public.player
    ADD FOREIGN KEY (team_id)
    REFERENCES public.team (team_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.match
    ADD FOREIGN KEY (type_id)
    REFERENCES public.type (type_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.match
    ADD FOREIGN KEY (team_one_id)
    REFERENCES public.team (team_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.match
    ADD FOREIGN KEY (team_two_id)
    REFERENCES public.team (team_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.result
    ADD FOREIGN KEY (match_id)
    REFERENCES public.match (match_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;